### ISSUE TITLE
OpenSSL 1.0.2k announced

### ISSUE THREAD

**Issue by Jan-E** [winlibs/openssl#1]
@weltling 

Forthcoming OpenSSL releases
============================

The OpenSSL project team would like to announce the forthcoming release of
OpenSSL versions 1.0.2k, 1.1.0d.

These releases will be made available on 26th January 2017 between approximately
1300-1700 UTC.  They will fix several security defects with maximum severity
"moderate".

Please see the following page for further details of severity levels:
https://www.openssl.org/policies/secpolicy.html

Please also note that, as per our previous announcements, support for 1.0.1
ended on 31st December 2016.

Yours

The OpenSSL Project Team

**Comment by weltling** [comment]
Thanks @Jan-E, i'm subscribed to the lists as well.

**Comment by Jan-E** [comment]
OK
