### ISSUE TITLE
Building 1.0.2 on AppVeyor

### ISSUE THREAD

**Issue by Jan-E** [winlibs/openssl#2]
@weltling
Take a look at https://github.com/Jan-E/OpenSSL-Fips
Build history: https://ci.appveyor.com/project/Jan-E/openssl-fips/history

You could use something like this for OpenSSL without Fips as well

**Comment by weltling** [comment]
Yeah, the automated building is a good idea. I was thinking about it as well, just that the effort was too big to implement it. Especially that teh way things are built would differ for different projects, etc. With AppVeyor, it might be ok for several libs, though one wouldn't be able to enforce several things like fe. an exact tools version.

Thanks.

**Comment by Jan-E** [comment]
> though one wouldn't be able to enforce several things like fe. an exact tools version.

When building Apache I am doing things like
```
for /R %%f in (*.vcxproj) do perl -pi.bak -e "s/v110/v141/gi" %%f
del *.vcxproj.bak /s >nul
```
This enforces the v141 toolset.

**Comment by weltling** [comment]
Clear, i mean technically it's doable in many ways. With the concrete compiler however i mean like what we have now with `1910`, `1911`, `1912`, etc. Often AppVeyor is slower so it has an older compiler.

Thanks.

**Comment by Jan-E** [comment]
For PHP this may be relevant, but for many of the deps like OpenSSL it is of no interest.

But you are right, AppVeyor is a bit slow. They are now at Visual Studio Community 2017 version 15.6.4. I am running 15.6.6 at the moment, but you are maybe already using 15.7.x.

Just wondering: is there a non-interactive command-line way to update Visual Studio Community 2017? If so, it could be used at AppVeyor as well.
